name: Scan Fortify SCA inside docker container

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: docker.io/evernow/fortify-sca:23.1
      options: --user root
      credentials:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWD }}
    steps:
      - name: Testes
        run: |
          curl -v https://update.fortify.com
          cat /etc/os-release
          yum install -y tar gzip
          echo $PATH
          ls -la /opt/fortify/plugins/maven
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run fortifyupdate
        run: fortifyupdate -url https://update.fortify.com
      - name: Run Fortify SCA clean
        run: sourceanalyzer -b webgoat -clean
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          architecture: x64
      - name: Setup Maven Action
        uses: stCarolas/setup-maven@v5
        with: 
          maven-version: 3.8.2
      #- name: Build with Maven 
      #  run: mvn -V
      - name: Intall Maven plugin
        run: |
          tar -xvzf /opt/fortify/plugins/maven/maven-plugin-bin.tar.gz
          mvn install:install-file -Dfile=pom.xml -DpomFile=pom.xml
          mvn install:install-file -Dfile=xcodebuild/pom.xml -DpomFile=xcodebuild/pom.xml
          mvn install:install-file -Dfile=sca-maven-plugin/sca-maven-plugin-23.1.0.jar -DpomFile=sca-maven-plugin/pom.xml
      - name: Run Fortify SCA translate
        run: sourceanalyzer -b webgoat mvn --no-transfer-progress verify
      - name: Run Fortify SCA scan
        run: sourceanalyzer -b webgoat -scan -f webgoat.fpr
      - name: Setup Fortify tools
        uses: fortify/github-action/setup@v1
        with:
          tool-definitions: https://github.com/fortify/tool-definitions/releases/download/v1/tool-definitions.yaml.zip
          export-path: true
          fcli: latest
      - name: Run fcli from PATH
        run: fcli -V
      - name: Run fcli using FCLI_CMD environment variable
        run: ${FCLI_CMD} -V
      - name: Login SSC do lab via FCLI
        run: fcli ssc session login --url=https://ssc.evernow.com.br/ --user ${{ secrets.SSC_USER }} --password ${{ secrets.SSC_PASSWD }}
      - name: Upload artifact via FCLI
        run: fcli ssc artifact upload --appversion=89 --file=webgoat.fpr
